services:
  mysql:
    image: mysql:8.0
    container_name: aether_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aether_db
      MYSQL_USER: aether_user
      MYSQL_PASSWORD: aether_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
